services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: tracekey_db_client
      POSTGRES_PASSWORD: 9708
      POSTGRES_DB: tracekey
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3101:3000"
    environment:
      DATABASE_URL: postgresql://tracekey_db_client:9708@db:5432/tracekey

volumes:
  pgdata:
