name: zap-tracekey
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: tracekey_db_client
      POSTGRES_PASSWORD: 9708
      POSTGRES_DB: tracekey
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3101:3000"
    networks:
      - app-network
    environment:
      POSTGRES_URL: postgresql://tracekey_db_client:9708@db:5432/tracekey
      CORS_ALLOWED_ORIGINS: http://localhost:3000,https://staging.customer.zapnow.tech,http://localhost:3001

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tracekey
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiMGY4YWE5MGMyZDQ3NGQwM2FkOWU4MzExOWE5ZTJhZjgiLCJ0IjoiOThiMTM3OWItZTk2Ni00M2YxLTg1MzEtOGMzODcyMTQzYzk3IiwicyI6Ik5ETmtNRFJqTjJFdFpEY3lNUzAwTXpCbExUa3hOR0V0WkRKbU1XSm1aalkwTkdSbSJ9
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
  
