name: zap-tracekey
services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: tracekey_db_client
      POSTGRES_PASSWORD: 9708
      POSTGRES_DB: tracekey
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql
    networks:
      - app-network

  app:
    restart: unless-stopped
    build: .
    depends_on:
      - db
    ports:
      - "3101:3000"
    networks:
      - app-network
    environment:
      POSTGRES_URL: postgresql://tracekey_db_client:9708@db:5432/tracekey

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tracekey
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token Cloudflare_Token
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
  
