-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.interactions
(
    api_key character(50) COLLATE pg_catalog."default" NOT NULL,
    ip_address character varying(40) COLLATE pg_catalog."default",
    user_agent character varying COLLATE pg_catalog."default",
    referrer_url character varying COLLATE pg_catalog."default",
    "timestamp" timestamp without time zone NOT NULL,
    device_information jsonb,
    cookies jsonb,
    interaction_id uuid NOT NULL,
    region character(1) COLLATE pg_catalog."default",
    device character(1) COLLATE pg_catalog."default",
    page_route character varying COLLATE pg_catalog."default" NOT NULL,
    action_name character varying COLLATE pg_catalog."default" NOT NULL,
    device_id character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT interactions_pkey PRIMARY KEY (interaction_id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    project_id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_by uuid NOT NULL,
    project_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    api_key character(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    site_url character varying(200) COLLATE pg_catalog."default",
    description character varying(300) COLLATE pg_catalog."default" DEFAULT 'No Description Provided'::character varying,
    CONSTRAINT projects_pkey PRIMARY KEY (project_id)
);

CREATE TABLE IF NOT EXISTS public.user_projects
(
    uuid uuid NOT NULL,
    project_id uuid NOT NULL,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_projects_pkey PRIMARY KEY (uuid, project_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    auth_key character varying(256) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (uuid),
    CONSTRAINT users_auth_key_key UNIQUE (auth_key),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.interactions
    ADD CONSTRAINT api_key_foregin_key FOREIGN KEY (api_key)
    REFERENCES public.projects (api_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT fk_created_by FOREIGN KEY (created_by)
    REFERENCES public.users (uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_project_created_by
    ON public.projects(created_by);

ALTER TABLE IF EXISTS public.user_projects
    ADD CONSTRAINT user_projects_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.user_projects
    ADD CONSTRAINT user_projects_uuid_fkey FOREIGN KEY (uuid)
    REFERENCES public.users (uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
